---
title: ""
---

&nbsp;

<!-- # {.tabset .tabset-fade .tabset-pills}  -->

<!-- ## Recent -->

## **Works in Progress**
&nbsp;

<!-- <span style="color: green;">**[NEW]**</span> -->

####  <a href="files/cahoots.pdf" target="_blank"> **Mobile Crisis Response Teams Support Better Policing: Evidence from CAHOOTS** </a> (with <a href="https://sites.google.com/site/jonathanmvdavis/" target="_blank">Jonathan Davis</a>, <a href="https://www.samuel-norris.com/" target="_blank">Samuel Norris</a>, Jadon Schmitt, and <a href="https://artsci.tamu.edu/economics/contact/profiles/chelsea-strickland.html" target="_blank">Chelsea Strickland</a> ) 


---

####  <a href="https://ekrose.github.io/files/lowwage_rs.pdf" target="_blank"> **How Replaceable Is a Low-Wage Job?** </a> (with <a href="https://ekrose.github.io/" target="_blank">Evan K. Rose</a>) 
#### <a href="https://www.nber.org/papers/w31447"> NBER Working Paper No. 31447, 2023 </a>
<!--  <a href="files/lowwage_rs.pdf" target="_blank"> **How Replaceable Is a Low-Wage Job?** </a> (with <a href="https://ekrose.github.io/" target="_blank">Evan K. Rose</a>) -->

#### Revision requested by the *Review of Economic Studies*  


---

<!-- <span style="color: green;">**[REVISED]**</span> -->

####    <a href="https://ekrose.github.io/files/rss_teachers_cjc.pdf" target="_blank"> **The Effects of Teacher Quality on Adult Criminal Justice Contact** </a>  (with  <a href="https://ekrose.github.io/" target="_blank">Evan K. Rose</a> and <a href="https://sites.google.com/view/jonathanschellenberg/" target="_blank">Jonathan Schellenberg</a>) 
#### <a href="https://www.nber.org/papers/w30274"> NBER Working Paper No. 30274, 2022 </a>

#### Revision requested by *Econometrica*  

&nbsp;

## **Publications**
&nbsp;

<!--  <span style="color: green;">**[NEW]**</span> -->
####  <a href="files/incar_lm.pdf" target="_blank"> **The Impact of Incarceration on Employment, Earnings, and Tax Filing** </a> (with <a href="https://sites.google.com/view/andygarin/home" target="_blank">Andrew Garin</a>, <a href="http://www.dmitrikoustas.com/" target="_blank">Dmitri Koustas</a> , <a href="https://carlmcpherson.github.io/" target="_blank">Carl McPherson</a>, <a href="https://www.samuel-norris.com/" target="_blank">Samuel Norris</a> , <a href="https://www.matthewpecenco.com/" target="_blank">Matthew Pecenco</a>, <a href="https://ekrose.github.io/" target="_blank">Evan K. Rose</a>, and <a href="https://www.jeff-weaver.com/" target="_blank">Jeffrey Weaver</a>)
#### <a href="https://www.nber.org/papers/w32747"> NBER Working Paper No. 32747, 2024 </a>; <a href="https://bfi.uchicago.edu/wp-content/uploads/2023/08/The-Impact-of-Incarceration-on-Employment-Earnings-and-Tax-Filing-1.pdf" target="_blank"> non-technical summary </a>
#### Accepted by *Econometrica*  


---

####  <a href="files/emco.pdf" target="_blank"> **On Recoding Ordered Treatments as Binary Indicators** </a>  (with  <a href="https://ekrose.github.io/" target="_blank">Evan K. Rose</a>)
#### <a href="https://www.nber.org/papers/w32234"> NBER Working Paper No. 32234, 2024 </a>
#### Accepted by the *Review of Economics and Statistics*  

---

#### <a href="files/deployments.pdf" target="_blank"> **The Effects of Combat Deployments on Veterans’ Outcomes** </a>  (with <a href="https://www.jessebruhn.com/" target="_blank">Jesse Bruhn</a>, <a href="https://sites.google.com/view/kyle-greenberg/home?authuser=0" target="_blank">Kyle Greenberg</a>, <a href="https://sites.google.com/site/matthewgudgeon/" target="_blank">Matthew Gudgeon</a>, and  <a href="https://ekrose.github.io/" target="_blank">Evan K. Rose</a>)
#### <a href="https://www.nber.org/papers/w30622?utm_campaign=ntwh&utm_medium=email&utm_source=ntwg30"> NBER Working Paper No. 30622, 2022 </a>
#### *Journal of Political Economy*, 2024  



---


#### <a href="files/MIR.pdf" target="_blank"> **Can Restorative Justice Conferencing Reduce Recidivism? Evidence From the Make-it-Right Program** (with  <a href="https://gspp.berkeley.edu/faculty-and-impact/faculty/steven-raphael" target="_blank">Steven Raphael</a> and <a href="https://www.capolicylab.org/staff/alissa-skog/" target="_blank">Alissa Skog</a>) 
#### <a href="files/MIR_online_appendix.pdf" target="_blank"> Online Appendix;  </a> <a href="https://www.nber.org/papers/w29150?utm_campaign=ntwh&utm_medium=email&utm_source=ntwg30" target="_blank"> NBER Working Paper No. 29150, 2021; </a> <a href="https://www.probablecausation.com/podcasts/episode-62-yotam-shem-tov" target="_blank"> Probable Causation Podcast </a>
#### *Econometrica*, 2024  


---


#### <a href="files/Shemtov_indigent_RESTAT.pdf" target="_blank">**Make or Buy? The Provision of Indigent Defense Services in the U.S.** </a> 
#### <a href="files/rest_a_00976-supp.pdf" target="_blank">Online Appendix</a>;    <a href="https://www.capolicylab.org/comparing-criminal-defense-brief/"target="_blank">Policy Brief by the California Policy Lab</a> 
#### *Review of Economics and Statistics*, 2022  

---

#### <a href="https://www.census.gov/library/working-papers/2021/adrm/CES-WP-21-14.html" target="_blank"> **School Discipline and Racial Disparities in Early Adulthood** </a> (with Miles Davison, <a href="http://www.socsci.uci.edu/~penner/" target="_blank">Andrew Penner</a> , <a href="https://emilykpenner.com/" target="_blank">Emily Penner</a>) , Nikolas Pharris-Ciurej, Sonya R. Porter, <a href="https://ekrose.github.io/" target="_blank">Evan K. Rose</a> , and Paul Yoo) 
#### *Educational Researcher*, 2022   

---

#### <a href="files/Rose_Shemtov_2021_Manuscript.pdf" target="_blank"> **How Does Incarceration Affect Reoffending? Estimating the Dose-Response Function**  </a>  (with <a href="https://ekrose.github.io/" target="_blank">Evan K. Rose</a>) 
#### <a href="files/Rose_Shemtov_2021_OnlineAppendix.pdf" target="_blank"> Online Appendix  </a>;   <a href="files/YotamShemTov_JMP.pdf" target="_blank"> JMP version  </a>  
#### *Journal of Political Economy*, 2021   



---


#### <a href="files/Sekhon_ShemTov_2020_JASA.pdf" target="_blank">**Inference on a New Class of Sample Average Treatment Effects**</a> (with <a href="https://www.jsekhon.com/" target="_blank">Jasjeet S. Sekhon</a>) 
#### *Journal of the American Statistical Association*, 2021

---

####  <a href="files/GagnonBartsch_and_ShemTov_2019_AOAS.pdf" target="_blank"> **The Classification Permutation Test: A Non-Parametric Test for Equality of Multivariate Distributions**</a> (with <a href="http://dept.stat.lsa.umich.edu/~johanngb/" target="_blank">Johann Gagnon-Bartsch</a>) 
#### *The Annals of Applied Statistics*, 2019.



&nbsp;

## **Pre-PhD Publications**
&nbsp;


#### <a href="http://www.sciencedirect.com/science/article/pii/S0165176515003705" target="_blank">**A note on fairness and personalised pricing**</a> (with Nir Vulkan) 
#### *Economics Letters*, 2015.

---

#### <a href="https://link.springer.com/article/10.1007/s11187-014-9619-8" target="_blank">**Entrepreneurs' Negotiation Behavior**</a> (with Sabrina Artinger and Nir Vulkan) 
#### *Small Business Economics*, 2015.

---

#### <a href="https://link.springer.com/article/10.1007/s10797-014-9335-y" target="_blank">**International Tax Competition: Zero Tax Rate at the Top Re-Established**</a> (with Tomer Blumkin and Efraim Sadka) 
#### *International Tax and Public Finance*, 2015.     

---

#### <a href="http://www.sciencedirect.com/science/article/pii/S0165176513002413" target="_blank">**A Case for Maximum Wage**</a> (with Tomer Blumkin and Efraim Sadka) 
#### *Economics Letters*, 2013.

---

 <!-- <a href="trilnick2014whatdrives.pdf" target="_blank">draft-<i class="fa fa-file-pdf-o" aria-hidden="true"></i></a> -->





